/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package simulacion;

import java.text.DecimalFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author Arles Cerrato, Jorge Morazán, Mario Raudales, Samir Facussé
 */
public class GUI extends javax.swing.JFrame {

    private Simulador simulador;
    
    public GUI() {
        initComponents();
        simulador = new Simulador();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ejecutar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        textResultado = new javax.swing.JTextArea();
        jcTipo = new javax.swing.JComboBox<>();
        textN = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ejecutar.setText("Ejecutar");
        ejecutar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ejecutarActionPerformed(evt);
            }
        });

        textResultado.setEditable(false);
        textResultado.setColumns(20);
        textResultado.setRows(5);
        jScrollPane1.setViewportView(textResultado);

        jcTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sin Cache", "Cache directo", "Cache asociativo", "Cache asociativo por conjuntos", "todos los tipos" }));

        textN.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jcTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23)
                        .addComponent(textN, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(ejecutar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ejecutar)
                    .addComponent(jcTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textN, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ejecutarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ejecutarActionPerformed
        simulador.inicioPuntero();
        simulador.cargarArrayRam();
        simulador.cargar_cache();
        String resultado = "Metodo\t\t Tiempo\n\n";
        int n;
        try {
            n = Integer.parseInt(textN.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Error no es un numero");
            return;
        }
        simulador.setTiempo(0);
        DecimalFormat df = new DecimalFormat("#.00");
        if (jcTipo.getSelectedIndex()==0){
            simulador.ordenar(jcTipo.getSelectedIndex(), n);
            resultado += "Sin Cache\t\t" + df.format(simulador.getTiempo());
        }
        else if (jcTipo.getSelectedIndex()==1){
            simulador.ordenar(jcTipo.getSelectedIndex(), n);
            resultado += "Cache Directo\t\t" + df.format(simulador.getTiempo());
        }
        else if (jcTipo.getSelectedIndex()==2){
            simulador.ordenar(jcTipo.getSelectedIndex(), n);
            resultado += "Asociativo\t\t" + df.format(simulador.getTiempo());
        }
        else if (jcTipo.getSelectedIndex()==3){
            simulador.ordenar(jcTipo.getSelectedIndex(), n);
            resultado += "Asociativo por conjuntos\t\t" + df.format(simulador.getTiempo());
        }
        else {
            simulador.ordenar(0, n);
            resultado += "Sin Cache\t\t" + df.format(simulador.getTiempo()) + "\n\n";
            simulador.setTiempo(0);
            simulador.cargar_cache();
            simulador.cargarArrayRam();            
            simulador.ordenar(1, n);
            resultado += "Cache Directo\t\t" + df.format(simulador.getTiempo()) + "\n\n";
            simulador.cargar_cache();
            simulador.cargarArrayRam(); 
            simulador.setTiempo(0);
            simulador.ordenar(2, n);
            resultado += "Asociativo\t\t" + df.format(simulador.getTiempo()) + "\n\n";
            simulador.cargar_cache();
            simulador.cargarArrayRam(); 
            simulador.setTiempo(0);
            simulador.ordenar(3, n);
            resultado += "Asociativo por conjuntos\t" + df.format(simulador.getTiempo()) + "\n\n";
        }
        textResultado.setText(resultado);
    }//GEN-LAST:event_ejecutarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ejecutar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jcTipo;
    private javax.swing.JTextField textN;
    private javax.swing.JTextArea textResultado;
    // End of variables declaration//GEN-END:variables
}
